-- FairySplit — schema and row-level security.
--
-- Paste this whole file into Supabase's SQL editor and run it once. It is the
-- ONLY definition of the database shape: nothing is created through the
-- dashboard UI, so this file and the database can never disagree.
--
-- Two settings are assumed, both chosen when the project was created:
--   * "Automatically expose new tables" OFF — so every table is invisible to
--     the API until granted below, on purpose.
--   * "Enable automatic RLS" ON — so a table is locked the moment it exists.
--     The explicit `enable row level security` lines below are belt and braces.
--
-- Money is integer centavos and rates are millicents, exactly as in the app.
-- Never numeric, never float: `bigint` all the way down.

begin;

/* -- who you are ----------------------------------------------------------
 * `profiles` mirrors auth.users so the app has somewhere to keep a display
 * name. It is NOT how a room knows your name — that is `members.name`, which
 * is per-room, because you might be "Phoebe" in one flat and "Ate Phoebe" in
 * another.
 * ---------------------------------------------------------------------- */

create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  created_at   timestamptz not null default now()
);

-- A profile row appears the moment somebody signs up, so the app never has to
-- cope with a signed-in user who has no profile.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Our own form writes display_name; Google sends full_name/name instead.
  -- Ours wins where present: a typed name was chosen, Google's was assigned.
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      ''
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

/* -- rooms and the people in them ---------------------------------------- */

create table if not exists public.rooms (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  -- 6 chars, alphabet excludes 0/O/1/I. Generated by the app, unique here.
  join_code          text not null unique,
  created_by         uuid not null references auth.users (id) on delete restrict,
  -- Dead weight: the UI dropped appliance defaults, but Room still carries the
  -- field. Kept so the type round-trips; safe to drop with the repo methods.
  appliance_defaults jsonb not null default '[]'::jsonb,
  created_at         timestamptz not null default now()
);

/*
 * `user_id` is NULLABLE on purpose.
 *
 * A member is a person in a room, which is not the same as an account. A
 * housemate can exist in the room before they have ever signed up — that is
 * what makes joining a *claim* rather than a duplicate appearing beside them.
 */
create table if not exists public.members (
  id         uuid primary key default gen_random_uuid(),
  room_id    uuid not null references public.rooms (id) on delete cascade,
  user_id    uuid references auth.users (id) on delete set null,
  name       text not null,
  created_at timestamptz not null default now()
);

-- One account is one person in a room. Two rows for the same account would
-- split somebody's own hours across two shares of the same bill.
create unique index if not exists members_room_user_idx
  on public.members (room_id, user_id)
  where user_id is not null;

create index if not exists members_room_idx on public.members (room_id);
create index if not exists members_user_idx on public.members (user_id);

/* -- logs ---------------------------------------------------------------- */

create table if not exists public.trackers (
  id         uuid primary key default gen_random_uuid(),
  room_id    uuid not null references public.rooms (id) on delete cascade,
  name       text not null,
  mode       text not null check (mode in ('clock', 'per_day', 'per_hour', 'per_cycle')),
  built_in   boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists trackers_room_idx on public.trackers (room_id, sort_order);

-- Exactly one built-in occupancy clock per room, forever.
create unique index if not exists trackers_one_builtin_idx
  on public.trackers (room_id)
  where built_in;

/*
 * A clock that is running right now.
 *
 * This is `runningSince` + `runningWith` from the app, as rows rather than two
 * parallel maps — they could never disagree here, and two people clocking in
 * at the same moment touch different rows instead of the same JSON blob.
 */
create table if not exists public.tracker_runs (
  tracker_id uuid not null references public.trackers (id) on delete cascade,
  member_id  uuid not null references public.members (id) on delete cascade,
  started_at timestamptz not null,
  -- Who the run will be charged to when it stops. Never empty.
  charged_to uuid[] not null,
  primary key (tracker_id, member_id)
);

/*
 * One finished amount: a clock run, or a number somebody typed.
 *
 * `participant_ids` is an array rather than a join table because the app only
 * ever reads whole entries — it never asks "which entries include Bea?"
 * independently. A join table would be the textbook answer and buy nothing.
 *
 * `quantity` is double precision, not numeric: it holds hours/days/cycles, and
 * a share of an entry split three ways is genuinely fractional. Money never
 * passes through here.
 */
create table if not exists public.log_entries (
  id              uuid primary key default gen_random_uuid(),
  tracker_id      uuid not null references public.trackers (id) on delete cascade,
  participant_ids uuid[] not null check (array_length(participant_ids, 1) > 0),
  quantity        double precision not null,
  started_at      timestamptz,
  ended_at        timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists log_entries_tracker_idx on public.log_entries (tracker_id);
-- Retention pruning and the bill's date window both scan by when it happened.
create index if not exists log_entries_started_idx on public.log_entries (tracker_id, started_at);

/* -- bills ---------------------------------------------------------------
 * The bill's own contents — appliances, uses, other charges — stay as jsonb.
 * They are edited as a unit inside one dialog by one person, so splitting them
 * into tables would buy concurrency nobody uses and cost three more joins.
 *
 * The PER-MEMBER facts get their own tables below, because those genuinely are
 * touched by different people at the same time (two housemates ticking "paid").
 * ---------------------------------------------------------------------- */

create table if not exists public.bills (
  id                uuid primary key default gen_random_uuid(),
  room_id           uuid not null references public.rooms (id) on delete cascade,
  kind              text not null check (kind in ('electricity', 'water', 'other')),
  name              text not null,
  total_centavos    bigint not null,
  round_up_to_peso  boolean not null default false,
  -- THE MODE SWITCH. null => simple split, no appliances.
  rate_millicents   bigint,
  due_on            date,
  starts_on         date,
  ends_on           date,
  appliances        jsonb not null default '[]'::jsonb,
  uses              jsonb not null default '[]'::jsonb,
  other_charges     jsonb not null default '[]'::jsonb,
  created_at        timestamptz not null default now()
);

create index if not exists bills_room_idx on public.bills (room_id, created_at desc);

-- Hand-entered hours that stand in for the occupancy clock, per bill.
-- An ABSENT row means "count the log" — which is why nothing here is nullable.
create table if not exists public.bill_member_hours (
  bill_id   uuid not null references public.bills (id) on delete cascade,
  member_id uuid not null references public.members (id) on delete cascade,
  hours     double precision not null,
  primary key (bill_id, member_id)
);

-- The same idea for every other log. Absent means the log is in charge.
create table if not exists public.bill_log_amounts (
  bill_id    uuid not null references public.bills (id) on delete cascade,
  tracker_id uuid not null references public.trackers (id) on delete cascade,
  member_id  uuid not null references public.members (id) on delete cascade,
  amount     double precision not null,
  primary key (bill_id, tracker_id, member_id)
);

-- Who has settled up. A row is a tick.
create table if not exists public.bill_paid (
  bill_id   uuid not null references public.bills (id) on delete cascade,
  member_id uuid not null references public.members (id) on delete cascade,
  primary key (bill_id, member_id)
);

/* -- the access helpers ---------------------------------------------------
 * These are SECURITY DEFINER, which is the whole point: a policy ON `members`
 * that queries `members` would recurse forever. Running as definer means the
 * inner query skips RLS and the recursion never happens.
 *
 * `set search_path = public` is not decoration — without it, someone who can
 * create objects could shadow a table name and change what these return.
 *
 * They live in `private` rather than `public` because PostgREST only exposes
 * `public`: in here they are simply not an API endpoint, while RLS can still
 * call them. In `public` they were reachable at /rest/v1/rpc/is_member_of by
 * anyone with the URL — Postgres grants EXECUTE on every new function to
 * PUBLIC by default, and `anon` inherits it. Nobody granted that; it is the
 * default nobody revokes.
 * ---------------------------------------------------------------------- */

create schema if not exists private;
grant usage on schema private to authenticated;

create or replace function private.is_member_of(p_room uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.members
    where room_id = p_room and user_id = auth.uid()
  );
$$;

create or replace function private.can_touch_tracker(p_tracker uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.trackers t
    join public.members m on m.room_id = t.room_id
    where t.id = p_tracker and m.user_id = auth.uid()
  );
$$;

create or replace function private.can_touch_bill(p_bill uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.bills b
    join public.members m on m.room_id = b.room_id
    where b.id = p_bill and m.user_id = auth.uid()
  );
$$;

/* -- row level security --------------------------------------------------
 * Every table, no exceptions. The shape is always the same: you can touch a
 * row if you are a member of the room it belongs to.
 * ---------------------------------------------------------------------- */

alter table public.profiles          enable row level security;
alter table public.rooms             enable row level security;
alter table public.members           enable row level security;
alter table public.trackers          enable row level security;
alter table public.tracker_runs      enable row level security;
alter table public.log_entries       enable row level security;
alter table public.bills             enable row level security;
alter table public.bill_member_hours enable row level security;
alter table public.bill_log_amounts  enable row level security;
alter table public.bill_paid         enable row level security;

-- profiles: yours alone. Other people's names come from `members.name`.
drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles
  for all using (id = auth.uid()) with check (id = auth.uid());

-- rooms: readable by its members. Created through create_room() below, which
-- is why there is no INSERT policy here — a bare insert would leave a room
-- with nobody in it, unreadable even by the person who made it.
drop policy if exists rooms_read on public.rooms;
create policy rooms_read on public.rooms
  for select using (private.is_member_of(id));

drop policy if exists rooms_write on public.rooms;
create policy rooms_write on public.rooms
  for update using (private.is_member_of(id)) with check (private.is_member_of(id));

drop policy if exists rooms_delete on public.rooms;
create policy rooms_delete on public.rooms
  for delete using (private.is_member_of(id));

drop policy if exists members_all on public.members;
create policy members_all on public.members
  for all using (private.is_member_of(room_id)) with check (private.is_member_of(room_id));

drop policy if exists trackers_all on public.trackers;
create policy trackers_all on public.trackers
  for all using (private.is_member_of(room_id)) with check (private.is_member_of(room_id));

drop policy if exists tracker_runs_all on public.tracker_runs;
create policy tracker_runs_all on public.tracker_runs
  for all using (private.can_touch_tracker(tracker_id))
  with check (private.can_touch_tracker(tracker_id));

drop policy if exists log_entries_all on public.log_entries;
create policy log_entries_all on public.log_entries
  for all using (private.can_touch_tracker(tracker_id))
  with check (private.can_touch_tracker(tracker_id));

drop policy if exists bills_all on public.bills;
create policy bills_all on public.bills
  for all using (private.is_member_of(room_id)) with check (private.is_member_of(room_id));

drop policy if exists bill_member_hours_all on public.bill_member_hours;
create policy bill_member_hours_all on public.bill_member_hours
  for all using (private.can_touch_bill(bill_id)) with check (private.can_touch_bill(bill_id));

drop policy if exists bill_log_amounts_all on public.bill_log_amounts;
create policy bill_log_amounts_all on public.bill_log_amounts
  for all using (private.can_touch_bill(bill_id)) with check (private.can_touch_bill(bill_id));

drop policy if exists bill_paid_all on public.bill_paid;
create policy bill_paid_all on public.bill_paid
  for all using (private.can_touch_bill(bill_id)) with check (private.can_touch_bill(bill_id));

/* -- creating and joining -------------------------------------------------
 * Both have to run privileged, for the same reason: RLS says you can only see
 * a room you are already in, and in both cases you are not in it yet.
 * ---------------------------------------------------------------------- */

/**
 * Make a room, put yourself in it, and give it its occupancy clock — all in
 * one transaction, so a half-made room can never exist.
 */
create or replace function public.create_room(p_name text, p_display_name text, p_join_code text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room   public.rooms;
  v_member uuid;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  insert into public.rooms (name, join_code, created_by)
  values (p_name, upper(p_join_code), auth.uid())
  returning * into v_room;

  insert into public.members (room_id, user_id, name)
  values (v_room.id, auth.uid(), p_display_name)
  returning id into v_member;

  -- Every room gets the built-in clock. The app never has to check.
  insert into public.trackers (room_id, name, mode, built_in, sort_order)
  values (v_room.id, 'Hours in the unit', 'clock', true, 0);

  return v_room;
end;
$$;

/**
 * Join by code.
 *
 * Already in the room? Hand it back unchanged — pressing join twice should not
 * make a second you. Otherwise add a member row for this account.
 */
create or replace function public.join_room(p_code text, p_display_name text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.rooms;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  select * into v_room from public.rooms where join_code = upper(trim(p_code));

  if not found then
    raise exception 'No room has that code';
  end if;

  if exists (
    select 1 from public.members
    where room_id = v_room.id and user_id = auth.uid()
  ) then
    return v_room;
  end if;

  insert into public.members (room_id, user_id, name)
  values (v_room.id, auth.uid(), p_display_name);

  return v_room;
end;
$$;

/* -- repository RPCs --------------------------------------------------------
 * Three more operations that touch more than one row and need to not
 * half-happen. Everything else the repository does is plain single-table
 * CRUD, which RLS already covers directly.
 *
 *   * start_clock / stop_clock read and write Postgres's own clock, not the
 *     browser's — a client with a wrong system clock should not be able to
 *     hand itself extra hours.
 *   * remove_member touches every bill and every log in the room, and a
 *     member's id also lives inside two JSONB arrays (bills.uses,
 *     bills.other_charges) that no foreign key reaches.
 * ---------------------------------------------------------------------- */

create or replace function public.start_clock(
  p_tracker_id uuid,
  p_member_id uuid,
  p_charged_to uuid[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not private.can_touch_tracker(p_tracker_id) then
    raise exception 'Not a member of this room';
  end if;

  insert into public.tracker_runs (tracker_id, member_id, started_at, charged_to)
  values (
    p_tracker_id,
    p_member_id,
    now(),
    case when array_length(p_charged_to, 1) > 0 then p_charged_to else array[p_member_id] end
  )
  on conflict (tracker_id, member_id) do nothing;
end;
$$;

create or replace function public.stop_clock(p_tracker_id uuid, p_member_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_started timestamptz;
  v_charged uuid[];
  v_ended   timestamptz := now();
  v_hours   double precision;
begin
  if not private.can_touch_tracker(p_tracker_id) then
    raise exception 'Not a member of this room';
  end if;

  delete from public.tracker_runs
  where tracker_id = p_tracker_id and member_id = p_member_id
  returning started_at, charged_to into v_started, v_charged;

  if v_started is null then
    return;
  end if;

  v_hours := extract(epoch from (v_ended - v_started)) / 3600.0;
  if v_hours <= 0 then
    return;
  end if;

  insert into public.log_entries (tracker_id, participant_ids, quantity, started_at, ended_at, created_at)
  values (
    p_tracker_id,
    case when array_length(v_charged, 1) > 0 then v_charged else array[p_member_id] end,
    v_hours,
    v_started,
    v_ended,
    v_ended
  );
end;
$$;

create or replace function public.remove_member(p_member_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_id uuid;
begin
  select room_id into v_room_id from public.members where id = p_member_id;
  if v_room_id is null then
    raise exception 'That person is no longer in this room';
  end if;
  if not private.is_member_of(v_room_id) then
    raise exception 'Not a member of this room';
  end if;

  update public.log_entries le
  set participant_ids = array_remove(le.participant_ids, p_member_id)
  from public.trackers t
  where t.id = le.tracker_id
    and t.room_id = v_room_id
    and p_member_id = any (le.participant_ids);

  delete from public.log_entries le
  using public.trackers t
  where t.id = le.tracker_id
    and t.room_id = v_room_id
    and array_length(le.participant_ids, 1) is null;

  update public.bills b
  set
    uses = (
      select coalesce(jsonb_agg(u2), '[]'::jsonb)
      from (
        select jsonb_set(
          u,
          '{participantIds}',
          (
            select coalesce(jsonb_agg(pid), '[]'::jsonb)
            from jsonb_array_elements_text(u -> 'participantIds') pid
            where pid <> p_member_id::text
          )
        ) as u2
        from jsonb_array_elements(b.uses) u
      ) filtered
      where jsonb_array_length(filtered.u2 -> 'participantIds') > 0
    ),
    other_charges = (
      select coalesce(jsonb_agg(
        case
          when c -> 'participantIds' = 'null'::jsonb then c
          else jsonb_set(
            c,
            '{participantIds}',
            coalesce(
              (
                select jsonb_agg(pid)
                from jsonb_array_elements_text(c -> 'participantIds') pid
                where pid <> p_member_id::text
              ),
              'null'::jsonb
            )
          )
        end
      ), '[]'::jsonb)
      from jsonb_array_elements(b.other_charges) c
    )
  where b.room_id = v_room_id;

  delete from public.members where id = p_member_id;
end;
$$;

/* -- grants ---------------------------------------------------------------
 * "Automatically expose new tables" is off, so nothing above is reachable
 * until it is named here. Note what is missing: `anon` gets NOTHING. Signed
 * out means no data, before RLS is even consulted.
 * ---------------------------------------------------------------------- */

grant usage on schema public to authenticated;

grant select, insert, update, delete on
  public.profiles,
  public.rooms,
  public.members,
  public.trackers,
  public.tracker_runs,
  public.log_entries,
  public.bills,
  public.bill_member_hours,
  public.bill_log_amounts,
  public.bill_paid
to authenticated;

-- Postgres hands EXECUTE on a new function to PUBLIC automatically, so every
-- one of these needs it taken away before anything is granted back.
revoke execute on function private.is_member_of(uuid)      from public;
revoke execute on function private.can_touch_tracker(uuid) from public;
revoke execute on function private.can_touch_bill(uuid)    from public;

-- An RLS policy expression runs as the QUERYING role, so `authenticated` must
-- be able to execute these or every read would fail with "permission denied".
grant execute on function private.is_member_of(uuid)      to authenticated;
grant execute on function private.can_touch_tracker(uuid) to authenticated;
grant execute on function private.can_touch_bill(uuid)    to authenticated;

-- A trigger function is never meant to be an endpoint. Triggers do not consult
-- EXECUTE, so revoking costs nothing.
revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- These two ARE endpoints, but only for somebody signed in. Both already
-- refuse when auth.uid() is null; this stops anon reaching them at all.
revoke execute on function public.create_room(text, text, text) from public, anon;
revoke execute on function public.join_room(text, text)         from public, anon;
grant  execute on function public.create_room(text, text, text) to authenticated;
grant  execute on function public.join_room(text, text)         to authenticated;

revoke execute on function public.start_clock(uuid, uuid, uuid[]) from public;
revoke execute on function public.stop_clock(uuid, uuid)          from public;
revoke execute on function public.remove_member(uuid)             from public;
grant  execute on function public.start_clock(uuid, uuid, uuid[]) to authenticated;
grant  execute on function public.stop_clock(uuid, uuid)          to authenticated;
grant  execute on function public.remove_member(uuid)             to authenticated;

-- And nothing anonymous gets to touch a table either.
revoke all on all tables in schema public from anon;

commit;
